### ISSUE TITLE
Build a Hass.io addon

### ISSUE THREAD

**Issue by sibbl** [sibbl/hass-lovelace-kindle-screensaver#1]
For devices with enough RAM and a good CPU, a Hass.io addon would make sense.

The code only requires Node.js and GraphicsMagick or ImageMagick to be installed. However, the Node.js server uses Puppeteer which again uses a Chromium binary.

As I'm using a Raspberry Pi for my Hass.io setup, having an addon doesn't make sense as it would slow down the whole system.
Maybe someone with a more powerful system might be able to help and lower the entry level.

**Comment by marciogranzotto** [comment]
I got a initial add-on working, but I want to be able to automatically get the API token instead of asking the user to enter it... I'll open a PR soon

**Comment by rxb** [comment]
It seems HASS OS doesn’t support portainer anymore. Any hints for alternate paths?

**Comment by marciogranzotto** [comment]
@rxb you can use my fork for now: https://github.com/marciogranzotto/hass-lovelace-kindle-screensaver

**Comment by sibbl** [comment]
I'm closing this issue since an Hassio addon was added via a PR. Thanks for that addition! We might want to improve it step by step, but as far as I heard it's working fine for a lot of users already!
