### ISSUE TITLE
Feature Request: Multiple Dashboards/Instances 

### ISSUE THREAD

**Issue by GraffJosh** [sibbl/hass-lovelace-kindle-screensaver#103]
Hi there! I'm using your addon for a bit of a different purpose, I feed the images to a thermal printer!
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/15370055/5866d8db-5446-4bc9-b3d4-6b806d22139a)

It works great for a single entity, but I'm hoping to diversify to multiple. I've considered switching the entity displayed on a conditional card, and that might work, but also having the ability to provide multiple instances of the add on, or multiple pages on the same server:
http://homeassistant.local:5000/image1 http://homeassistant.local:5000/image2 would be an interesting way to accomplish the same. 

Thanks for your hard work! Great add on!

**Comment by sibbl** [comment]
Hey, what a unique use case! Great to see that it's flexible enough to also work this way 👍 

This feature already should be working. In the most simple way, you can add `HA_SCREENSHOT_URL_2`, `HA_SCREENSHOT_URL_3`, ... `HA_SCREENSHOT_URL_n` and can then access this image via `http://homeassistant.local:5000/2`, `http://homeassistant.local:5000/3`, ..., `http://homeassistant.local:5000/n´.

You can append this `_n` suffix to all variables which have "Array" = "yes" in the configuration table you can find in the [README](https://github.com/sibbl/hass-lovelace-kindle-screensaver/blob/main/README.md#usage).
