### ISSUE TITLE
HA OS 32bit not supported?

### ISSUE THREAD

**Issue by mph070770** [sibbl/hass-lovelace-kindle-screensaver#105]
My HA install is quite old but, to date hasn't caused any issues.  I believe it's HA OS (although I can't remember how I installed it on my RPI4) and the version page is a bit confusing for me:

Core   2024.1.3
Supervisor   2023.12.1
Operating System    11.4
Frontend    20240104.0

I added your SW via add ons, and get the following error when I try to install:

Add-on a877bbfb_kindle-screensaver not supported on this platform, supported architectures: aarch64, amd64

Is only 64 bit supported?  If so, I'll have to migrate HA to 64 bit?

**Comment by beeh5** [comment]
Hi @sibbl 
Thanks for taking this up so quickly, much appreciated!
I tried installing it via the HA Add-On store on my Raspberry Pi 3, but I keep getting the following error message when clicking on "Install". 

```
 Can't install sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7:1.0.6: 404 Client Error for http+docker://localhost/v1.43/images/sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7:1.0.6/json: Not Found ("No such image: sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7:1.0.6") 
``` 

I run HaOS on a Raspi 3, Hypervisor and HA itself are all up-to-date. Your [build](https://hub.docker.com/layers/sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7/1.0.6/images/sha256-4ed6bd5a5e28a6f6688aac8aa70c0967f90b0a40f48e1f94f69391af131b4c1e?context=explore) has been transferred to the Docker Hub successfully, so that can't be the issue. I saw other people having [similar issues](https://github.com/home-assistant/supervisor/issues/4402) with installing other ARMv7 Add-Ons, so the issue may be on my part. I keep investigating, but I will provide feedback once I make it run.

**Comment by sibbl** [comment]
Hey @beeh5, thanks for the feedback.

Indeed it's very strange that it shows a 404... it could also be an indicator that `armv7` is not correct... if the architecture is wrong, then docker also shows a 404.

Not sure how to proceed with the problem. I saw that some images use `arm/v7` instead - do you think it may be worth another try? I could try to generate this in a branch and ping you to give it another try. 

But it's good to see that the download is now possible, so it's really "just" a problem of how I tag and upload it to the Docker hub.

PS: Raspi 3 also supports 64bit HaOS, doesn't it? Maybe backup -> reinstall -> restore backup is quicker? Just an idea 😄

**Comment by beeh5** [comment]
Hi @sibbl 

To rule out an issue on my specific instance: @mph070770 can you successfully install the latest version of hass-lovelace-kindle-screensaver on your 32-Bit RPi4 instance via the AddOn-Store? 

@sibbl I will have a look at the logs of the hypervisor once I get [root ssh access](https://developers.home-assistant.io/docs/operating-system/debugging/) up and running. If there is a way I can install a specific branch in the Add-On store, I can gladly give it a try. 

While the Raspi 3 supports 64bit, I have found [community reports](https://community.home-assistant.io/t/wth-is-the-64-bit-version-on-raspberry-pi-3-the-recommended-version/473993) stating that it runs anything but smoothly. Given that I have not made the switch so far.

**Comment by beeh5** [comment]
@sibbl haven't had a chance to go through the supervisor logs. Will get back at it once I get home from vacation.

**Comment by beeh5** [comment]
Hi @sibbl 

I have dug some more into the issue of installing your HA Add-On on a 32bit ARMv7 Raspberry Pi 3. Today I tried to manually install the HomeAssistant Add-On in a hypervisor shell. This resulted in the following output: 

```
# docker pull sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7
Using default tag: latest
latest: Pulling from sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7
no matching manifest for linux/arm/v7 in the manifest list entries
```

In inspecting the manifest I found that the Add-On describes the platform like this: 
```
# docker manifest inspect sibbl/hass-lovelace-kindle-screensaver-ha-addon-armv7
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         // ...
         "platform": {
            "architecture": "armv7",
            "os": "linux"
         }
      },
      // ...
   ]
}
```

I tried running your other container `sibbl/hass-lovelace-kindle-screensaver` on the Raspi 3 which resulted in no such error messages...  :) There you define the platform slightly differently:  

```
# docker manifest inspect sibbl/hass-lovelace-kindle-screensaver
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         // ...
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      // ...
   ]
}
```

Could this hint at the fix required?

**Comment by sibbl** [comment]
@beeh5 thanks for these insights! I wasn't aware that there might be a difference, but I've tried the newer `arm/v7` syntax for the hass addon. It's currently building and I hope it finally works then: https://github.com/sibbl/hass-lovelace-kindle-screensaver/actions/runs/8143869860

Please let me know and thanks for your help!

**Comment by beeh5** [comment]
Hi @sibbl 
Thanks for taking it up so quickly! I was now able to install it successfully via the HomeAssistant Add-On Store!
Thanks and cheers to you! 👍
