### ISSUE TITLE
How to select which theme to take?

### ISSUE THREAD

**Issue by raphael303** [sibbl/hass-lovelace-kindle-screensaver#114]
I use a theme which looks like this (part of it):
<img width="1014" alt="image" src="https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/60788818/5a7bb168-d97a-4569-85d1-0554eefa9997">

and the above dashboard is rendered like this:
<img width="811" alt="image" src="https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/60788818/08cde3ea-6d19-4800-9bfc-198b0d08c698">

As you can see, the height is not the same. Let alone the shape of the tiles. 
How can I make it use that theme?

**Comment by raphael303** [comment]
never mind. if I select a bright theme for the dashboard it takes that. But, man, it looks horrible. So I stick with the original one it defaults to.

**Comment by sibbl** [comment]
I hope you found a theme which fits. The only thing which I can offer is some kind of eink theme in this repo: https://github.com/sibbl/hass-lovelace-kindle-screensaver/blob/main/lovelace-eink-theme.yml

I'm using it myself, but it's far from supporting all edge cases of e.g. custom lovelace components like the left one.
