### ISSUE TITLE
Feature Check - ARM Builds

### ISSUE THREAD

**Issue by rgegriff** [sibbl/hass-lovelace-kindle-screensaver#115]
Hi! I think I can update the github action to build for both X86_64 and various ARM archs.

If I opened up a PR that did that, would you be likely to accept it?

Just wanted to check first in case there was a specific case against it.

**Comment by sibbl** [comment]
Hi @rgegriff, generally I'd be happy about any additions!

May I ask whether there is a specific architecture you're missing or have a problem when trying to use the project?

So far we support amd64, arm64/v8 and arm/v7 - which correlates to the availability of [pre-built chromium alpine packages](https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.18&repo=&arch=&maintainer=).
