### ISSUE TITLE
"Loading data" after first image generation

### ISSUE THREAD

**Issue by WegnerDan** [sibbl/hass-lovelace-kindle-screensaver#124]
After restarting the addon, it works and generates the wanted image:

![Untitled-1](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/6908247/ae57fba7-ea65-48a7-8bde-c0569ce40a16)

After a while, it just displays "loading data" perpetually:

![Untitled](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/6908247/df30aca8-a08f-406c-a39d-d317fd0aba62)

<details>
<summary>Logs</summary>

```
Starting browser...
Visiting 'http://nucky:8123' to login...
Adding authentication entry to browser's local storage...
Starting first render...
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
Starting rendering cronjob...
Server is running at 5000
2024-05-11T13:55:44.063Z: Image 1 was accessed
Invalid request: /favicon.ico for page NaN
2024-05-11T13:55:45.833Z: Image 1 was accessed
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
2024-05-11T13:57:12.173Z: Image 1 was accessed
2024-05-11T13:57:37.048Z: Image 1 was accessed
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
2024-05-11T13:59:12.176Z: Image 1 was accessed
Rendering http://nucky:8123/dashboard-displays/0?kiosk to image...
Converting rendered screenshot of http://nucky:8123/dashboard-displays/0?kiosk to grayscale...
Finished http://nucky:8123/dashboard-displays/0?kiosk
2024-05-11T14:00:02.022Z: Image 1 was accessed
Invalid request: /favicon.ico for page NaN
```

</details>

Found this maybe related issue: https://github.com/sibbl/hass-lovelace-kindle-screensaver/issues/15 

I've played with the RENDERING_DELAY parameter, but it doesn't help. Tried 5, 10, 100 and 1000 as delay, but it doesn't seem to change anything.

config:
![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/6908247/4aa36418-3dbb-48b7-9614-1d7b70c55dff)

Anybody else have this problem?

**Comment by WegnerDan** [comment]
RENDERING_DELAY set to 10000 seems to fix it.

**Comment by sibbl** [comment]
Thanks for the feedback! 10000 ms, which is 10s, rendering delay indeed makes sense - especially for slower devices which I guess is used here.

At some point the browser just tells this tool "I'm done with the first render of the website" but i.e. Javascript is still executed. Depending on how much data is still loaded and then needs to be drawn, this can take up to 10s or more.

To be safe, I could imagine that 15-20s may also be a reasonable value there (so 15000 or 20000 ms as the input value).

**Comment by WegnerDan** [comment]
It worked fine without any delay before the most recent home assistant update ( https://github.com/home-assistant/core/releases/tag/2024.5.3 ), that's why I didn't close this issue.

Also, not really a slow device. I'm using the mainboard of a framework laptop with an i5-1135G7. (Not great, not terrible lol)

I think there might be something going wrong in the addon, which now necessitates the delay
