### ISSUE TITLE
Add x-time-rendered header

### ISSUE THREAD

**Issue by degan6** [sibbl/hass-lovelace-kindle-screensaver#14]
Hello!

Thank you for making such an awesome tool, I was able to get it up and running in docker in minutes!

It would be awesome to add a header to the response that says when the image was rendered.

I'd like to add some simple monitoring to be alerted if the service crashes and stops refreshing the image.

**Comment by sibbl** [comment]
@degan6 thanks for your feature request!

I've just released a new version which now adds a `Last-Modified` header. The last modification date of the image is passed in the HTTP date format. I hope this helps :)
