### ISSUE TITLE
Invalid request to /output/cover.png

### ISSUE THREAD

**Issue by Pattern91** [sibbl/hass-lovelace-kindle-screensaver#21]
Hey,
i just reinstalled your docker container on a raspberry pi 3 with portainer via docker-compose. When i start your plugin everything is fine but when i want to look up the rendered image i get this error message:

"Invalid request to /output/cover.png"

Do you have an idea?

Thank you for your help!

**Comment by Pattern91** [comment]
I figured it out by myself... in a previous Version the rendered image was available via :5000/output/cover.png no in this version it is available just via :5000


That took me a few hours to get this^^

**Comment by sibbl** [comment]
Thanks for your reply and the update how you could fix it.

Yes indeed, earlier versions and especially the former project [hass-kindle-screensaver](https://github.com/sibbl/hass-kindle-screensaver/) (different repo, although the name is similar) was just made for one single image and returned it when requesting any path - including the one you mentioned.
