### ISSUE TITLE
convert: unrecognized dither method `-background' @ error/convert.c/ConvertImageCommand/1403.`

### ISSUE THREAD

**Issue by blockarchitech** [sibbl/hass-lovelace-kindle-screensaver#30]
When using dithering, the error 
```
convert: unrecognized dither method `-background' @ error/convert.c/ConvertImageCommand/1403. 
``` 
Is thrown, using the latest version of the docker image.

**Comment by MartinLindenau** [comment]
With 1.0.5 the same problem.

**Comment by cannondale0815** [comment]
Confirming the same in add-on 1.0.7 still:

`Starting browser...
Visiting 'http://192.168.1.10:8123' to login...
Adding authentication entry to browser's local storage...
Starting first render...
Rendering http://192.168.1.10:8123/dashboard-kindle/0 to image...
Converting rendered screenshot of http://192.168.1.10:8123/dashboard-kindle/0 to grayscale png...
/app/node_modules/gm/lib/command.js:301
          err = new Error('Command failed: ' + stderr);
                ^

Error: Command failed: convert: unrecognized dither method `-background' @ error/convert.c/ConvertImageCommand/1422.

    at ChildProcess.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Pipe.<anonymous> (node:net:350:12) {
  code: 1,
  signal: null
}
`

**Comment by cannondale0815** [comment]
@sibbl Hi Sebastian, seems like an older issue -- just wanted to call attention to it as it seems to be buried all the way at the bottom. Thanks mate!

**Comment by sibbl** [comment]
Hi @cannondale0815 the error from version 1.0.7 was kind of related to this one, but I'd like to keep this one open.

In addition, I'd like to quote my findings from the other bug report:

> The cause of this might be that our Dockerfile uses imagemagick instead of graphicsmagick. While the [used npm module `gm`](https://www.npmjs.com/package/gm) says to be compatible with both, it doesn't seem to support the differences in the `dither` parameter. While `+dither` works for both, [the `-dither` parameter requires the name of the dither algorithm to use in imagemagick](https://legacy.imagemagick.org/Usage/quantize/#dither_how), while [graphicsmagick only uses it as a toggle](http://www.graphicsmagick.org/GraphicsMagick.html#details-dither).
> 
> Maybe it's worth to give Graphicsmagick another try in the Dockerfile but I'm not sure what other incompatibilities will occur. An alternative would be to open an issue in the gm npm package repository. Finally, we could also just use the "custom arguments" feature of the gm npm package to support `-dither ALGORITHM` and ´+dither` by our own. That's probably what I'd prefer.

https://github.com/sibbl/hass-lovelace-kindle-screensaver/issues/112#issuecomment-1960877672

So probably the last option might also finally solve this issue here.

**Comment by blockarchitech** [comment]
I totally forgot I had this open! Thanks again, @sibbl !
