### ISSUE TITLE
Step-by-step tutorial how to use this?

### ISSUE THREAD

**Issue by franzuu** [sibbl/hass-lovelace-kindle-screensaver#32]
Hi! 
First of all thank you for creating this cool project!
I'm gonna say that I'm a total noob with docker and Command-line interface and would like to ask some step-by-step guidance how to set this up.

Docker is installed on raspberry pi and I was able to pull the container by `docker pull sibbl/hass-lovelace-kindle-screensaver`
but when I try to run it with `docker run sibbl/hass-lovelace-kindle-screensaver` it displays this message:

> pi@raspberrypi:~ $ docker run sibbl/hass-lovelace-kindle-screensaver

> hass-lovelace-kindle-screensaver@1.0.4 start 
> node index.js
> 
> Please check your configuration
> npm notice 
> npm notice New minor version of npm available! 8.1.0 -> 8.5.5
> npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
> npm notice Run `npm install -g npm@8.5.5` to update!
> npm notice 

I guess it says I need to add HA information somewhere, but how is this done?

**Comment by sibbl** [comment]
Hi @franzuu,

sorry for the quite late response.

Probably I should move the following sentence in the README.md a bit up? 
> You may also simply use the docker-compose.yml file inside this repository, configure everything in there and run `docker-compose up`.

I'd appreciate if you could report back whether you were able to set it up using this instruction and if not, I'd offer to add some hints about it.

**Comment by dabepp** [comment]
> I'd appreciate if you could report back whether you were able to set it up using this instruction and if not, I'd offer to add some hints about it.

I would like to have some hints, how to install this on a supervised environment...
