### ISSUE TITLE
Kindle won't display Image

### ISSUE THREAD

**Issue by DerPicknicker** [sibbl/hass-lovelace-kindle-screensaver#34]
Hello again, 

the Docker-Container works now.. But the Kindle won't display the Image. The LOG-File, seems good, but in the Docker log, there is now message that the Picture is downloaded.. 

Screen is just blank and nothing to see.. 

Here is the Kindle-Log: 

Fri Apr 22 12:01:28 GMT+01:59 2022: START NEW LOOP
Fri Apr 22 12:01:28 GMT+01:59 2022: Set CPU scaling governer to powersave
Fri Apr 22 12:01:28 GMT+01:59 2022: Set prevent screen saver to true
Fri Apr 22 12:01:28 GMT+01:59 2022: Battery: isCharging=0 percentage=43% current=-24 mA
Fri Apr 22 12:01:28 GMT+01:59 2022: Remaining battery 43
Fri Apr 22 12:01:28 GMT+01:59 2022: Enabling and checking wifi
Fri Apr 22 12:01:29 GMT+01:59 2022: Connected to wifi
Fri Apr 22 12:01:29 GMT+01:59 2022: Found default gateway 192.168.178.1
Fri Apr 22 12:01:29 GMT+01:59 2022: Ping worked successfully
Fri Apr 22 12:01:29 GMT+01:59 2022: Download result
Fri Apr 22 12:01:29 GMT+01:59 2022: Screen saver image file updated
Fri Apr 22 12:01:30 GMT+01:59 2022: Removed temporary files
Fri Apr 22 12:02:00 GMT+01:59 2022: SUCCESS, will update again on 1650621720

**Comment by dmfarcas** [comment]
here's the issue that I had -- the kindle could not resolve "homeassistant.local" , so the wget would silently fail. logged looked very similar to yours.
Please try to use your host's ip address instead of host name.
I figured this by ssh-ing into the kindle and doing a wget manually there. The wget would fail :)

**Comment by DerPicknicker** [comment]
> here's the issue that I had -- the kindle could not resolve "homeassistant.local" , so the wget would silently fail. logged looked very similar to yours.
> Please try to use your host's ip address instead of host name.
> I figured this by ssh-ing into the kindle and doing a wget manually there. The wget would fail :)

I tried that already - i changed to another tutorial from the the FHEM - Community .. I used this Docker image to create just the image to display… The image was available via ip-address… I checked it with different devices

**Comment by dmfarcas** [comment]
Same! It worked from my pc. For Some reason the Kindle Didnt resolve the HA Ip address. 
For future Reference, if anyone gets stuck, wgetting the image manually on the kindle might be a good debugging start point

**Comment by DerPicknicker** [comment]
That’s a good point! 

But: I didn’t use the HOSTNAME… For me it wasn’t possible to get this running. The addon shows on the display that wifi is not connected but the image could not be displayed. So in the end I gave up and choose a different option… The docker image works fine but the kindle addon not :(

**Comment by dmfarcas** [comment]
Gah, coding. If something can go wrong, it will go wrong🥲

**Comment by sibbl** [comment]
@DerPicknicker were you able to resolve the kindle issue meanwhile? As you got the container working, I'd suggest to close this issue and perhaps continue discussing in https://github.com/sibbl/hass-lovelace-kindle-4

Thanks :)
