### ISSUE TITLE
Add option to reset zoom?

### ISSUE THREAD

**Issue by mitchsurp** [sibbl/hass-lovelace-kindle-screensaver#40]
When using the kiosk javascript (?kiosk at the end of a URL) in HomeAssistant, many browsers including node-js will be default render a bar at the top where the header would normally be. You can see this in my work-in-progress here.

![energy3](https://user-images.githubusercontent.com/19660494/171762116-5559d53c-08b1-4090-a750-69f10370a430.png)

This sacrifices around 10% of the image. The only way I've found to fix this in any browser is to zoom (in or out, it doesn't matter) and then reset to default. The bar goes away and the image fills the entire frame. This is entirely reproducible by loading kiosk.js (maykar/kiosk-mode) and accessing a URL with ?kiosk appended.

Is there any way to build an option to do this?

**Comment by sibbl** [comment]
Hi @mitchsurp,

I can recommend setting your lovelace tab to "panel" view in the tab's settings.
This will allow you to only have one single card, which then has no borders/paddings/margins at its sides.
This single component can then be a vertical stack card.

I hope this helps!

**Comment by mitchsurp** [comment]
I did find a way to fix this. It turns out that kiosk mode was abandoned or forked, and a new version created in HACS. This version loads without the bar. This is no longer an issue.

**Comment by sibbl** [comment]
@mitchsurp thanks for the update! I also was looking for a replacement for the archived old kiosk mode extension. I guess this is the one you now use? https://github.com/NemesisRE/kiosk-mode

I'll also update it in my readmes.
