### ISSUE TITLE
Docker container time

### ISSUE THREAD

**Issue by SurfingSpider** [sibbl/hass-lovelace-kindle-screensaver#41]
I have a stange case where I have a Home assistant dashboard with a calender on it. The time of the apointments are all offset by an hour when rendered by the docker container. 

I suspect it is because of daylight saving or something. It I consle into the docker container and use the "date" command I see this is also an hour out and set to UTC time. I am in the uk and we are currently on BST British summer time.

Is there a way I can set the docker container to use BST not UTC?

**Screenshot of kindle (NOTE I write into some event titles the times as well)**
![192 168 86](https://user-images.githubusercontent.com/11552822/180421281-18ca2db7-1b55-45f5-a017-4ce92c9a0551.png)

**Screen shot of output of home assistant**
![Screenshot 2022-07-22 113339](https://user-images.githubusercontent.com/11552822/180422199-b1f2653f-5ecc-4018-9413-0e17a3341788.jpg)

**Comment by sibbl** [comment]
Yes, Docker allows you to set the `TZ=Europe/London` environment variable.

**Comment by SurfingSpider** [comment]
Prefect. I just tried this and it worked. Thank you
