### ISSUE TITLE
Unable to connect to Home Assistant.

### ISSUE THREAD

**Issue by sonnleit** [sibbl/hass-lovelace-kindle-screensaver#44]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/57795107/192581312-86c0a0bc-ab0e-46a8-9a0b-640faf611c3f.png">

I always get this error.

my config: 

<tbody>
            <tr>
              <td>Image</td>
              <td><a ui-sref="docker.images.image({ id: container.Image, nodeName: nodeName })" class="ng-binding" href="#!/2/docker/images/sha256%3A57b11f1cafedd5b4f1d87a2a3827cd0aeec1f755cf7ae53e1bd5614346a61865">sibbl/hass-lovelace-kindle-screensaver:latest</a></td>
            </tr>
            
            <tr>
              <td>CMD</td>
              <td><code class="ng-binding">npm start</code></td>
            </tr>
            <tr>
              <td>ENTRYPOINT</td>
              <td><code class="ng-binding">docker-entrypoint.sh</code></td>
            </tr>
            <tr>
              <td>ENV</td>
              <td>
                <table class="table table-bordered table-condensed">
                  <tbody><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">COLOR_MODE</td>
                    <td class="ng-binding">GrayScale</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">CRON_JOB</td>
                    <td class="ng-binding">* * * * *</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">GRAYSCALE_DEPTH</td>
                    <td class="ng-binding">16</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">HA_ACCESS_TOKEN</td>
                    <td class="ng-binding">ZMytoken</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">HA_BASE_URL</td>
                    <td class="ng-binding">http://homeassistant.local:8123/</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">HA_SCREENSHOT_URL</td>
                    <td class="ng-binding">lovelace/1</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">LANGUAGE</td>
                    <td class="ng-binding">de</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">NODE_VERSION</td>
                    <td class="ng-binding">16.13.0</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">PATH</td>
                    <td class="ng-binding">/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">PUPPETEER_EXECUTABLE_PATH</td>
                    <td class="ng-binding">/usr/bin/chromium-browser</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">PUPPETEER_SKIP_CHROMIUM_DOWNLOAD</td>
                    <td class="ng-binding">true</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">RENDERING_DELAY</td>
                    <td class="ng-binding">10000</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">RENDERING_SCREEN_HEIGHT</td>
                    <td class="ng-binding">800</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">RENDERING_SCREEN_WIDTH</td>
                    <td class="ng-binding">600</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">RENDERING_TIMEOUT</td>
                    <td class="ng-binding">40000</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">ROTATION</td>
                    <td class="ng-binding">0</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">SCALING</td>
                    <td class="ng-binding">1</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">UNSAFE_IGNORE_CERTIFICATE_ERRORS</td>
                    <td class="ng-binding">true</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">USE_IMAGE_MAGICK</td>
                    <td class="ng-binding">true</td>
                  </tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope">
                    <td class="ng-binding">YARN_VERSION</td>
                    <td class="ng-binding">1.22.15</td>
                  </tr>
                </tbody></table>
              </td>
            </tr>
            <tr ng-if="!(container.Config.Labels | emptyobject)" class="ng-scope">

**Comment by archont00** [comment]
Same here. NC 23 behind Nginx SSL proxy.

When I tried to run the container with env "DEBUG=true" (to find out more), it fails with NPM error.

```
ha36-screenshot  | > node index.js                                                                                                  
ha36-screenshot  |                                                                                                                  
ha36-screenshot  | Starting browser...                                                                                              
ha36-screenshot  | /app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203                                          
ha36-screenshot  |             reject(new Error([                                                                                   
ha36-screenshot  |                    ^
ha36-screenshot  | 
ha36-screenshot  | Error: Failed to launch the browser process!
ha36-screenshot  | [29:29:0928/201319.914801:ERROR:browser_main_loop.cc(1485)] Unable to open X display.
```

**Comment by archont00** [comment]
Try removing the trailing `/` from `HA_BASE_URL` and add it as a prefix to `HA_SCREENSHOT_URL` instead... Then, it works for me.
