### ISSUE TITLE
Having trouble getting container started (docker compose)

### ISSUE THREAD

**Issue by fernplant** [sibbl/hass-lovelace-kindle-screensaver#46]
I edited the compose yaml and ran the command

> docker compose up -d
> [+] Running 10/10
>  ⠿ app Pulled                                                                                                                                                                 35.3s
>    ⠿ 083a2a44b72d Pull complete                                                                                                                                                1.4s
>    ⠿ 28d22366df91 Pull complete                                                                                                                                                9.7s
>    ⠿ 1c06832cd72a Pull complete                                                                                                                                               10.3s
>    ⠿ c20d24f1d426 Pull complete                                                                                                                                               10.6s
>    ⠿ 188dd0e0b943 Pull complete                                                                                                                                               10.8s
>    ⠿ 38282be6cefd Pull complete                                                                                                                                               30.9s
>    ⠿ dc0858d0e9e1 Pull complete                                                                                                                                               31.2s
>    ⠿ e902242f485d Pull complete                                                                                                                                               33.4s
>    ⠿ cdb32c37ee88 Pull complete                                                                                                                                               33.6s
> [+] Running 2/2
>  ⠿ Network hass-lovelace-kindle-screensaver_default  Created                                                                                                                   0.5s
>  ⠿ Container hass-lovelace-kindle-screensaver-app-1  Started                                                                                                                   1.7s

But port 5000 not reachable and no output in output dir. Checking to see if container is running and it appears not to be

>pi@homeassistant:~/src/hass-lovelace-kindle-screensaver $ docker compose ls
>NAME                STATUS              CONFIG FILES

I am admittedly terrible with docker and understanding whats happening. Im assuming its something Im doing wrong. Are there logs I can check? There are no errors generated. Any help would be greatly appreciated

**Comment by sibbl** [comment]
Hi,  you can actually use `docker compose logs -f` to follow the logs (remove the `-f` for fetching recent logs instead of watching).

I guess there might be something wrong with the config.

**Comment by fernplant** [comment]
Thanks for the helping hand! Yes, it is indeed throwing an error in logs and thats why its not working

> Visiting 'https://homeassistant.local:8123' to login...
> hass-lovelace-kindle-screensaver-app-1  | /app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155
> hass-lovelace-kindle-screensaver-app-1  |                     ? new Error(`${response.errorText} at ${url}`)
> hass-lovelace-kindle-screensaver-app-1  |                       ^
> hass-lovelace-kindle-screensaver-app-1  | Error: net::ERR_NAME_NOT_RESOLVED at https://homeassistant.local:8123

My URL is not reachable by the container. I changed it to the IP address instead and then that complained about SSL so removed the https and then it worked!

Thanks very much again for your help and for this project
