### ISSUE TITLE
Emoji Support?

### ISSUE THREAD

**Issue by totalitarian** [sibbl/hass-lovelace-kindle-screensaver#48]
Currently have an calendar with an emojoi in the title 

![image](https://user-images.githubusercontent.com/2385696/212559847-9d997e21-0006-48bc-9920-b79eedde4c91.png)

but it gets displayed like so...

![image](https://user-images.githubusercontent.com/2385696/212559872-8671db84-56e8-4071-8640-fff17f13a9ce.png)

Any ideas?

**Comment by sibbl** [comment]
@totalitarian thanks for the report. Indeed the current image didn't include an emoji font, so there was nothing to be shown.

I've just added a font, although I'm not 100% happy about it as it's not optimized for grayscale. Nevertheless, it's better than having those question marks being rendered.

So please update your container image to the latest one and it should be working 👍

**Comment by totalitarian** [comment]
Many thanks!
