### ISSUE TITLE
Adjust font size in e-ink theme.

### ISSUE THREAD

**Issue by brewston** [sibbl/hass-lovelace-kindle-screensaver#50]
I just got this working on my PW2 - Thanks !

It's quite small to read the text on it though. I'm using mushroom title card to display various bits of text. Would it be possible to have a font size adjustment in the theme itself ? I'm not familiar enough with CSS.

**Comment by sibbl** [comment]
Hi @brewston, thanks for your feedback!

Did you play around with the SCALING config option already?

You can e.g. set it to 1.5 to achieve the same affect like setting the zoom level in your desktop browser to 150%.

**Comment by brewston** [comment]
That worked nicely ! Danke schoen.
