### ISSUE TITLE
Online Screensaver Extension not compatible

### ISSUE THREAD

**Issue by smitterer** [sibbl/hass-lovelace-kindle-screensaver#55]
Hi,

I wanted to use the online screensaver extension but this says it needs a URL ending with an image extension like .png (see conf.sh).
As this repo only provides the image without the file ending, I can't get it to work (at least that's my guess)

Is there any way to use the filename ?

Thanks

**Comment by sibbl** [comment]
Hi @smitterer,

you can safely point the image path to this project server URL (e.g. `http://localhost:5000/`  or `http://localhost:5000/2`).

The endpoint will return a valid png image, even if it doesn't have a .png image extension in the URL.

**Comment by smitterer** [comment]
> Hi @smitterer,
> 
> you can safely point the image path to this project server URL (e.g. `http://localhost:5000/` or `http://localhost:5000/2`).
> 
> The endpoint will return a valid png image, even if it doesn't have a .png image extension in the URL.

Ok thanks for your reply.
Then it must be something else in my case, because I can't get it to show the image on my lockscreen while the ScreenSavers Hack is showing the image that the extension (ScreenSavers, not Online ScreenSavers) is working.

I will try to find any other non-https image and try it with that.

**Comment by sibbl** [comment]
What exaclty is the "ScreenSavers Hack" you mention? I'm having no troubles with both [my own customized kindle 4 extension](https://github.com/sibbl/hass-lovelace-kindle-4) as well as the [Online screensaver extension](https://www.mobileread.com/forums/showthread.php?t=236104) which are both linked in this repository's readme.

**Comment by smitterer** [comment]
https://wiki.mobileread.com/wiki/Kindle_Screen_Saver_Hack_for_all_2.x,_3.x_%26_4.x_Kindles that's the one I'm talking about.
I get the "The ScreenSavers hack has been succesfully installed" thing.

If I manually save the image generated by your project into /linkss/screensavers, it's showing up.

But nothing is downloaded and I'm not sure if that's a problem with this repository (which is does not seem to be) or with the online screensaver extension or, most likely, a config-error. Also I can't find any log file.

This is my conf:
```

#############################################################################
### ONLINE-SCREENSAVER CONFIGURATION SETTINGS
#############################################################################

# Interval in MINUTES in which to update the screensaver by default. This
# setting will only be used if no schedule (see below) fits. Note that if the
# update fails, the script is not updating again until INTERVAL minutes have
# passed again. So chose a good compromise between updating often (to make
# sure you always have the latest image) and rarely (to not waste battery).
DEFAULTINTERVAL=30

# Schedule for updating the screensaver. Use checkschedule.sh to check whether
# the format is correctly understood. 
#
# The format is a space separated list of settings for different times of day:
#       SCHEDULE="setting1 setting2 setting3 etc"
# where each setting is of the format
#       STARTHOUR:STARTMINUTE-ENDHOUR:ENDMINUTE=INTERVAL
# where
#       STARTHOUR:STARTMINUTE is the time this setting starts taking effect
#       ENDHOUR:ENDMINUTE is the time this setting stops being active
#       INTERVAL is the interval in MINUTES in which to update the screensaver
#
# Time values must be in 24 hour format and not wrap over midnight.
# EXAMPLE: "00:00-06:00=480 06:00-18:00=15 18:00-24:00=30"
#          -> Between midnight and 6am, update every 4 hours
#          -> Between 6am and 6pm (18 o'clock), update every 15 minutes
#          -> Between 6pm and midnight, update every 30 minutes
#
# Use the checkschedule.sh script to verify that the setting is correct and
# which would be the active interval.
SCHEDULE="00:00-24:00=15"

# URL of screensaver image. This really must be in the EXACT resolution of
# your Kindle's screen (e.g. 600x800 or 758x1024) and really must be PNG.
#IMAGE_URI="http://enter.the.domain/here/and/the/path/to/the/image.png"
IMAGE_URI="http://192.168.0.45:5500/"

# folder that holds the screensavers
SCREENSAVERFOLDER=/mnt/us/linkss/screensavers/

# In which file to store the downloaded image. Make sure this is a valid
# screensaver file. E.g. check the current screensaver folder to see what
# the first filename is, then just use this. THIS FILE WILL BE OVERWRITTEN!
SCREENSAVERFILE=$SCREENSAVERFOLDER/bg_ss00.png

# Whether to create log output (1) or not (0).
LOGGING=1

# Where to log to - either /dev/stderr for console output, or an absolute
# file path (beware that this may grow large over time!)
#LOGFILE=/dev/stderr
LOGFILE=/mnt/us/tmp/onlinescreensaver.log

# whether to disable WiFi after the script has finished (if WiFi was off
# when the script started, it will always turn it off)
DISABLE_WIFI=1

# Domain to ping to test network connectivity. Default should work, but in
# case some firewall blocks access, try a popular local website.
TEST_DOMAIN="http://192.168.0.1/"

# How long (in seconds) to wait for an internet connection to be established
# (if you experience frequent timeouts when waking up from sleep, try to
# increase this value)
NETWORK_TIMEOUT=30



#############################################################################
# Advanced
#############################################################################

# the real-time clock to use (0, 1 or 2)
RTC=0

# the temporary file to download the screensaver image to
TMPFILE=/tmp/tmp.onlinescreensaver.png

```

**Comment by sibbl** [comment]
You should be able to run `cat /mnt/us/tmp/onlinescreensaver.log` or `tail -n 50 /mnt/us/tmp/onlinescreensaver.log` via ssh to check the log output. If it's empty, it's not running. Straight from the config the log is enabled and it should be written to.
