### ISSUE TITLE
Trouble with local and language settings

### ISSUE THREAD

**Issue by toluen-kodekrets** [sibbl/hass-lovelace-kindle-screensaver#60]
This was a great and fun project. But I have trouble setting locale and language, as shown here in the calender card with both the time beeing with AM/PM and the dates/days in english. Any tips in getting these to be in Norwegian Bokmål?

![bilde](https://user-images.githubusercontent.com/114817086/227205640-32a659c7-3c06-4199-b4d0-2ad74d14bc56.png)

**Comment by sibbl** [comment]
I'd recommend to set this in the profile page of the HA user, which you've created the auth token for: https://my.home-assistant.io/redirect/profile

There, language, time format, number format and first day of week can be set.

Additionally, Docker provides setting the timezone via the `TZ=Europe/Berlin` environment variable.

As far as I know, this should resolve all the localization troubles, but please let me know if something else might be required.

**Comment by toluen-kodekrets** [comment]
Thank you so much, works for all but the language for the days and the months in the calender, strange. But this will do. Here is the finished product. Did some bad measurments, but still happy with the result.
![bilde](https://user-images.githubusercontent.com/114817086/227332018-352dea13-b5e6-4d25-b135-9e1be8747177.png)
