### ISSUE TITLE
Cosmetic Add-On Bug: HA_BASE_URL in Asterisk/hidden

### ISSUE THREAD

**Issue by The-May** [sibbl/hass-lovelace-kindle-screensaver#66]
I have added this Repo as Home Assistant Addon and it was recognized without any problem.
It works without any problem but I stumbled upon a config value that is in asterisk (hidden) characters which in my opinion should not be:
![grafik](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/47433911/83fad16d-94dd-4eb6-b781-7f75dbc7532e)
Especially when the "hidden" value is shown in the logs as plain text.

Luckily the logs show if the path is right or not:
![grafik](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/47433911/c68b8c8c-dafe-4fd7-a450-fe0c81da09c7)

This makes it harder to type in the string, but not impossible.

Thanks alot for merging and making it extremely easier for non tech savvi ppl.

**Comment by sibbl** [comment]
Hey, thanks for pointing this out and giving feedback about the newly added addon!

Indeed I guess the base URL might not have to be hidden. Maybe we could even find a solution to automatically get this (and the token) so it's an optional input you only need to fill if you really want to use a different Hass instance.

Not sure when I'll find time as it doesn't seem high prio for now, but it's definitely something we should improve.
