### ISSUE TITLE
Configurable wake up interval

### ISSUE THREAD

**Issue by tomasz8w** [sibbl/hass-lovelace-kindle-screensaver#77]
Hi,
Thanks for this project, it brought new life to my old Kindle and made it super useful :) 
I wondering if this is something doable (but I guess it should be in similar way like the battery hook is working) to provide a way to change waking up interval. Use case scenario: update Kindle screen rarely when nobody is home or during the night.
What do you think about this?

**Comment by sibbl** [comment]
Hey @tomasz8w,

thanks for your kind words.

If you want to use this kind of extended configuration, I'd recommend using the [online screensaver extension](https://www.mobileread.com/forums/showthread.php?t=236104) which allows you to configure a schedule as you want.

I'd personally see this as some kind of extended configuration and for those, who want this extended configuration, this extension might be the best choice.

Finally, let me also tell you that my Kindle 4 has been running for more than 4 years now with a screen refresh every minute and it's still working like a charm. These eink displays Amazon integrated there are simply awesome!

**Comment by tomasz8w** [comment]
Hey,
Thanks for the link, I'll definitely take a look and see if that fits my needs. 

I use my kindle wirelessly as it stands in a place where I haven't possibility to power it permanently and currently as I set update interval to 10mins it lasts for about 5 days. That led me to opening this ticket as container used here is already authenticated in HA. Not sure about linked solution but I'll investigate it and hopefully find some solution to extend battery cycle.

**Comment by sibbl** [comment]
The linked project is a kindle extension, which I've forked and adapted for the [kindle 4](https://github.com/sibbl/hass-lovelace-kindle-4). 

Both actually just point to an URL, where they regularly fetch the image from. So 90% should be the same and work just as well with this image rendering server here, as the kindle 4 one does.

Good luck, I hope it will turn out well and give you a much better battery life!

**Comment by tomasz8w** [comment]
Good to know that both projects are so similar. Thanks again!
