### ISSUE TITLE
Possible to use non-integer values for 'Scaling' attribute?

### ISSUE THREAD

**Issue by TomAnks** [sibbl/hass-lovelace-kindle-screensaver#78]
Hi! I wondered if it was possible to use a non-integer value for 'Scaling' in the configuration? 

The documentation states that Scaling factor can be: e.g. 1.5 to zoom in or 0.75 to zoom out.

However, when I try to set the value as a non-integer, e.g. 0.75, the configuration does not let me save the value and it does not work.

![scaling pic](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/26800901/1815a111-3cfe-4031-8bad-594e78eb2d9d)

**Comment by fall88** [comment]
I am experiencing the same, would like to zoom out as well

**Comment by dabepp** [comment]
I tried 1.5 and the system changes it to 1,5. If I use 2 it is way too big. A little bit bigger would be fine...

**Comment by dabepp** [comment]
I also would like to see a zoom factor of 1.2

**Comment by paulchevalier** [comment]
It looks like the problem is in the config.yaml file of the extension, where the scaling variable is declared as an integer.

**Comment by sibbl** [comment]
> It looks like the problem is in the config.yaml file of the extension, where the scaling variable is declared as an integer.
> 
> Edit: I forked the repo on my personal github, fixed the issue, tested that it works for me, and submitted a pull request to close this issue.
> 
> Many thanks to @sibbl for this great addon!

Thanks for the PR! It's merged so I hope with the new version which is automatically being built right now, the issue can be closed.

I'd appreciate it, if someone else can confirm that it's working as I don't have this tool running as an addon but as a standalone docker container on another machine instead.

**Comment by TomAnks** [comment]
Happy to test out the code change. @sibbl Should I expect to see the update in HA directly or do I need to download the new version from Github and add into HA?

**Comment by dabepp** [comment]
I have a bunch of updates within the addons, the Screensaver is none of them... How do I get the latest version?

**Comment by TomAnks** [comment]
> > Happy to test out the code change. @sibbl Should I expect to see the update in HA directly or do I need to download the new version from Github and add into HA?
> 
> Did you find a way to get the latest version?

I haven't seen any update come through in HA yet. This Kindle project took a lot of hours for me to implement so I'm wary of downloading the version straight from GitHub in case it wipes my config and anything else I might have configured while setting this up.

**Comment by dabepp** [comment]
> I haven't seen any update come through in HA yet. T

I just de- and reinstalled via the "Add repository"-Button on the github page and it did seem to work.
It still shows Version 1.05 so maybe it already does work for you, too.
From Germany I used 1,5 with a comma as seperator. Your milage may vary.

Only thing I don't like is that it still shows 600 width and larger letters, I was more into scaling it to be a little bit wider to get the border of some pixels utilized...

**Comment by sibbl** [comment]
Seems like I forgot to bump the version string in one of the files. A new container is building right now, not having any new features but this new version string 1.0.6. Sorry about this - I didn't think of it when I merged the changes directly before going on vacation...

**Comment by TomAnks** [comment]
Updated, tested, and confirmed working. Thanks @sibbl for making my dreams of a correctly-scaled dashboard come true!
