### ISSUE TITLE
HassOS: read only filesystem

### ISSUE THREAD

**Issue by Pattern91** [sibbl/hass-lovelace-kindle-screensaver#8]
I tried installing this container on a HassOS based System using a raspberry pi.
Although i define a directory as readable and writable i get an error message that the directory for the docker container can't be created. I used the Portainer Hassio Addon to intall the container.

Does anyone have an advice?

**Comment by marciogranzotto** [comment]
I think you have to disable the Protection Mode on Portainer

**Comment by Pattern91** [comment]
I already activated the "unsafe"-mode and restarted portainer but it didn't change anything...

**Comment by marciogranzotto** [comment]
I don't know if it helps, but here's my container config:
![image](https://user-images.githubusercontent.com/11080704/112730015-dbce2880-8f0d-11eb-91bc-2161fd41cf3d.png)

![image](https://user-images.githubusercontent.com/11080704/112729991-bd682d00-8f0d-11eb-9b7a-607826a40a09.png)

**Comment by Pattern91** [comment]
Do you use HassOS or a Hass.up installation on raspberry lite?
Can you show your volume settings of this container?

**Comment by Pattern91** [comment]
What is your output path?

**Comment by Pattern91** [comment]
I got it working! I created a volume manually within portainer and used the directory path in the container output path settings
