### ISSUE TITLE
Screenshots from 2 or more Dashbaords

### ISSUE THREAD

**Issue by 4noxx** [sibbl/hass-lovelace-kindle-screensaver#81]
How can i made a Screenshot from a second Dashboard?

Regard

**Comment by sibbl** [comment]
Hi @4noxx,

you can configure `HA_SCREENSHOT_URL_2`, `HA_SCREENSHOT_URL_3`, ... in your config (as well as `ROTATION_2`, `ROTATION_3`, ...).

This allows more screenshots being taken.

Finally, you can access these images by appending the number to the URL. E.g. `http://localhost:5000/2` or `http://localhost:5000/3`

**Comment by 4noxx** [comment]
and different are also possible? need this for a 4" and 7" screen

**Comment by sibbl** [comment]
Please check the readme. There is a table with all config options. In all rows, where "Array?" is set to "yes", you can append `_2`, `_3` etc. 

I.e. you can also specify `RENDERING_SCREEN_HEIGHT_2` and `RENDERING_SCREEN_WIDTH_2` for different sizes, as well as `SCALING_2`, too. If there is no corresponding `_2`, `_3`, ... config set in your container, the default one (without _2, _3, ...) will be used.
