### ISSUE TITLE
webhook not triggering

### ISSUE THREAD

**Issue by micdis** [sibbl/hass-lovelace-kindle-screensaver#89]
Hi! first of all: thanks for your nice work! :- )

I don't get the web hook running for batteryLevel.
I did configure the webhook ID, but the script seems not to trigger or send data to this webhook.

I do get a update in the protocol:

`New battery level: 100 for page 1`

and as a sidenote: the AddOn does not show itself as running in HA, but keeps the "red" flag on the top right and the script asks for "Start"

**Comment by gdst4rp** [comment]
I've noticed that it crashes sometimes at startup. Check the Logs tab and you may need to refresh the AddOn page to see if it's actually still running.

**Comment by micdis** [comment]
no, it is not on the list, but I checked "Only accessible from the local network" because it does not need to be exposed.

I can manually trigger the webhook and it does work. The AddOn just does not!?

**Comment by sibbl** [comment]
Hey all,

I'm personally not using the HA addon so I may only be able to give you some technical insights.

What's internally done: the URL is built in the way that `{HA_BASE_URL}/api/webhook/{HA_BATTERY_WEBHOOK}` is used as the URL. A POST request with `{ batteryLevel: 50, isCharging: false }` is sent there.

I'll try to add some logging to the addon in the next version to investigate this further, but maybe you can manually trigger this via curl or so and do some further testing meanwhile?

**Comment by micdis** [comment]
Hi!

got it working. First: the option for "Only accessible from the local network" must NOT be checked in order for it to work (not sure why) and the second thing is: the web hook gets triggered not on the picture download to the kindle, but on the next PNG-update from the AddOn.

So for the moment everything works fine. Thanks again for your help and efforts! :- )
