### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by dmutpuul** [sibbl/hass-lovelace-kindle-screensaver#93]
Hello. Thank you very much for great addon. I am using it to generate screenshot of some cards and send to telegram.
Is it possible to add dark mode to browser setting or some arguments for browser ?
Find something about that, but i don't where to change that on my server)

`async function renderUrlToImageAsync(browser, pageConfig, url, path) {
  let page;
  try {
    page = await browser.newPage();
    await page.emulateMediaFeatures([
      {
        name: "prefers-color-scheme",
        value: "light"
      }
    ]);`

**Comment by deenter** [comment]
@dmutpuul please check the latest version, the dark mode feature is now available via #97

**Comment by dmutpuul** [comment]
@deenter Hello! Have no updates so i reinstalled addon. I have preferred color option in config, but it doesn't work( still no dark screenshots...

**Comment by deenter** [comment]
Seems to be an issue when using it directly as an addon via HACS,
using the latest docker image everything works as expected for me.
