### ISSUE TITLE
Setting theme

### ISSUE THREAD

**Issue by matejdro** [sibbl/hass-lovelace-kindle-screensaver#99]
Is there a way to set [Home Assistant's theme](https://www.home-assistant.io/integrations/frontend/#manual-theme-selection) when taking screenshots?

For me, it always appears to default to backend selected theme, even if I change the theme on the user that owns the supplied token.

My default backend theme is dark, which does not look best on e-ink displays, so I would like kindle screensaver to take screenshot of the default theme instead of my deafult selected one.

**Comment by sibbl** [comment]
That's interesting - I would have thought that the theme would be applied if it's set to something different for the user.

I'm not sure how this is exactly stored inside HA, but if it works after logging in with this user in a private mode, it should also work here. I would've expected that HA loads the theme from the backend and applies it, but I have no idea about the exact behavior and how it's intended to be.

For now, this is also not planned for this add-on. I'd like to reuse as many default features of HA and maybe of other plugins like the kiosk plugin to hide stuff.

Is it maybe a valid option to set the theme for only the dashboard tab you're taking a screenshot? I have one dedicated tab only for e-ink and have set the theme for this single tab to a non-default one. This definitely works and also allows you to optimize the UI specifically for the e-ink device as well.

If you share the same tab with other devices, we might want to find another solution though. We should take a look the "per user theme setting" is not applied then, first.

**Comment by matejdro** [comment]
It looks like theme is stored per-session not per-user (after logging in in private mode, it reverts to default backend-selected theme). It appears this is stored in javascript's local storage:

![image](https://github.com/sibbl/hass-lovelace-kindle-screensaver/assets/507922/97dac294-47b0-49a5-818c-a443e19b95d9)

> Is it maybe a valid option to set the theme for only the dashboard tab you're taking a screenshot? I

Unfortunately, this only works for setting custom HA theme. My (dark only) theme is already custom and I want to use stock theme for eink.

But thanks for the suggestion, I have managed to work this around by creating a "custom" theme that is essentially just the default theme: https://community.home-assistant.io/t/default-theme/219278/11 and this one can be selected per-tab. As far as I'm concerned, my issue is solved. Thanks!
